<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'DDEV\\TestPackageInitialization\\Command\\SettingsCleanupCommand' => $typo3InstallDir . 'typo3conf/ext/test_package_initialization/Classes/Command/SettingsCleanupCommand.php',
);
